{{- if .Values.ssm.parameterValue }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-managed.fullname" . }}-env
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "app-managed.labels" . | nindent 4 }}
type: Opaque
stringData:
  PARAMS_STORE: {{ .Values.ssm.parameterValue | quote }}
{{- end }}
