apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-managed.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "app-managed.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "app-managed.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
